CREATE DATABASE DB_WineHouse;
USE DB_WineHouse;

CREATE TABLE `user`(
	id_user INT NOT NULL AUTO_INCREMENT,
    mail VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    id_address INT NOT NULL,
    name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id_user, mail)
);
CREATE TABLE `address`(
	id_address INT NOT NULL AUTO_INCREMENT,
	country VARCHAR(50) NOT NULL,
    province VARCHAR(50) NOT NULL,
	CONSTRAINT PK_ADDRESS PRIMARY KEY (id_address)
);
CREATE TABLE `page`(
	id_page INT NOT NULL AUTO_INCREMENT,
    search VARCHAR(20) NOT NULL,
    info TEXT NOT NULL,
	CONSTRAINT PK_PAGE PRIMARY KEY (id_page)
);
CREATE TABLE `history`(
	id_history INT NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    search VARCHAR(20) NOT NULL,
    CONSTRAINT PK_HISTORY PRIMARY KEY (id_history)
);
CREATE TABLE `data`(
	id_data INT NOT NULL AUTO_INCREMENT,
    id_user INT NOT NULL,
	date DATE NOT NULL,
    id_history INT NOT NULL,
    id_page INT NOT NULL,
	CONSTRAINT PK_DATA PRIMARY KEY (id_data)
);


ALTER TABLE user ADD CONSTRAINT FK_USER_ADDRESS FOREIGN KEY FK_USER_ADDRESS (id_address)
	REFERENCES address (id_address);
ALTER TABLE data ADD CONSTRAINT FK_DATA_HISTORY FOREIGN KEY FK_DATA_HISTORY (id_history)
	REFERENCES history (id_history);
ALTER TABLE data ADD CONSTRAINT FK_DATA_USER FOREIGN KEY FK_DATA_USER (id_user)
	REFERENCES user (id_user);
ALTER TABLE data ADD CONSTRAINT FK_DATA_PAGE FOREIGN KEY FK_DATA_PAGE (id_page)
	REFERENCES page (id_page)